// <auto-generated />
using Meta_Ads_World.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meta_Ads_World.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241023105205_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Meta_Ads_World.Data.BrandCategoryMst", b =>
                {
                    b.Property<int>("bcategoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bcategoryid"));

                    b.Property<string>("bcategoryname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("bcategorystatus")
                        .HasColumnType("bit");

                    b.HasKey("bcategoryid");

                    b.ToTable("BrandCategoryMst");
                });

            modelBuilder.Entity("Meta_Ads_World.Data.BrandRegistrationMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("bcity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bconfirmpassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bcontactno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bcountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bpassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bstate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("bstatus")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("BrandRegistrationMst");
                });

            modelBuilder.Entity("Meta_Ads_World.Data.UserMst", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userid"));

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("ucity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uconfirmemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uconfirmpassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ucountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ufname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ulname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urefreallcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("urefreallid")
                        .HasColumnType("int");

                    b.Property<string>("ustate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userid");

                    b.ToTable("UserMsts");
                });
#pragma warning restore 612, 618
        }
    }
}
